### ISSUE TITLE
Whatsapp

### ISSUE THREAD

**Issue by GamiDPC** [socialAPIS/WhatsApp-API#1]
Hello, is there a telegram?

**Comment by socialAPIS** [comment]
No, this is a repo for WhatsApp.

**Comment by GamiDPC** [comment]
I know this, do you have telegram contacts?

**Comment by elvislakota** [comment]
Yes i have?

**Comment by socialAPIS** [comment]
Yes i have telegram?

**Comment by GamiDPC** [comment]
Leave your contacts I have a few questions

**Comment by socialAPIS** [comment]
Please write on elvisstudioss@gmail.com and i will send you my email. And i have to update this repo the exist request is nearly done. It works beside of the libsignal prekeys. Maybe your question is answered in the next commit
