### ISSUE TITLE
Maybe Github will close this repo because of Copy-write Issues

### ISSUE THREAD

**Issue by shekohex** [socialAPIS/WhatsApp-API#2]
Hello, I'm interesting in Whatsapp API, but i notice that you are using the `about_logo.png` which is the whatsapp logo !

I know the purpose of that image, and i also worked on rev-eng the whatsapp code it self.
but i think github may take that seriously if some one reported that repo of using something protected by copy-write for that.

I would suggest convert that image to some sort of other format, say `pingo.dat` file which contains the `base64` text of that image.

Thank you !

**Comment by socialAPIS** [comment]
Im not home and i dont have here a computer. You can create a pull request if you want.
Im already developing an dll extension to replace the java thing.
And i will post when im home the java script code.
Can you please create a pull request for the `about_logo.png`
