### ISSUE TITLE
Help for the project

### ISSUE THREAD

**Issue by modcastro** [socialAPIS/WhatsApp-API#3]
I have built a similar project, but I am facing difficulties with the token.

I get error 401 when trying to login. What do you know about it?

Strangeness this happened now to a new number, to another old number still working.

@socialAPIS   Thanks for your help

``
private $header = "\x57\x41\x02\x00";
	private $certificatePublicKey = "\xF7\x42\x48\xD2\xE8\xC4\x72\x06\x0F\x5B\x39\xE9\xE0\xCC\x76\xC3\x38\x3F\xAB\x94\xF6\x91\x0F\xCC\xD0\xDB\x60\xB3\x57\x5C\x69\x08";

	public function __construct(WhatsProt $parent, $password)
	{

		$this->parent = $parent;
		$this->password = $password;
		$this->writer = $this->parent->getWriter();
		$this->reader = $this->parent->getReader();
		$this->name = $this->parent->getPushname();
		$this->socket = $this->parent->getSocket();
		$this->settings = $this->parent->getSettings();
		$this->phoneNumber = $this->parent->getMyNumber();
		$this->ephemeralPublic = base64_decode($this->settings->get("static_public_key"));
		$this->ephemeralPrivate = base64_decode($this->settings->get("static_private_key"));
	}

	public function doLogin()
	{
		$this->writer->resetKey();
		$this->reader->resetKey();
		socket_write($this->socket, $this->header);

		if (strlen(base64_decode($this->settings->get("server_static_public_key", ""))) == 32) {
		  $this->sendClientResume();

		}
		else {
		  $this->sendClientHello();

		}
	}

	protected function ValidateCertificate($certificate, $details)
	{

		if ($details->get(NoiseCertificate_Details::ISSUER) != "WhatsAppLongTerm1") {
			return false;
		}

		return curve25519_verify($this->certificatePublicKey, $certificate->get(NoiseCertificate::DETAILS), $certificate->get(NoiseCertificate::SIGNATURE)) == 0;
	}

``

**Comment by socialAPIS** [comment]
You cant base64 encode in php

Im writing a lib for base64 rfc 2045
Php default is using something different.
In 3-4 month i will post it here when it is done.

**Comment by modcastro** [comment]
great @socialAPIS  My project is ready and functional. Creating new passwords and logging in normally. I just could not figure out why some new numbers it gets random error 401. 

I'll keep following here. Thanks

**Comment by socialAPIS** [comment]
How you have done the end to end encryption? With the keys?

**Comment by modcastro** [comment]
@socialAPIS send your e-mail I share with you my code.

**Comment by socialAPIS** [comment]
elundelneuedition@gmail.com

**Comment by socialAPIS** [comment]
Just to tell this api is not using the web.whatsapp.com

If you have read and understand how the ete encryption works on the private api works then please share.

I don't have time to work on this and if you help me i will post some new code.

elundelneuedition@gmail.com

**Comment by beshoo** [comment]
@modcastro  did you manage to solve this issue?
I am struggling like you to run wahtsapp as an restfull api, i will be happy to have your email address. 
Beshoo@gmail.com 

Regard
